import PageHero from "@/components/heros/PageHero";
import NewsLetter from "@/components/NewsLetter";
import Services from "@/components/Services";
import MembersCounter from "@/components/MembersCounter";
import Pricing from "@/components/Pricing";
export const metadata = {
  title: "SFGCO  Investments",
  description: "Generated by SFGCO",
};
export default function ServicePage() {
  return (
    <>
      <PageHero
        // subtitle="OUR Investments"
        title="The world’s best companies <br> trust SFGCO  "
        paragraph="Until recently, the prevailing view assumed lorem ipsum was born as a nonsense text. It's not Latin, though it looks like it"
      />
      <Services sectionDetails={false} />
      <NewsLetter />
    </>
  );
}
