import PageHero from "@/components/heros/PageHero";
import NewsLetter from "@/components/NewsLetter";
import Investments from "@/components/Investments";

export const metadata = {
  title: "SFGCO  Investments",
  description: "Generated by SFGCO",
};
export default function InvestmentsPage() {
  return (
    <>
      <PageHero
        subtitle="OUR Investments"
        // title="The world’s best companies <br> trust SFGCO  "
        paragraph="That's great to hear! Investing in technology and waste management aligns perfectly with the growing demand for sustainable solutions and will likely position your company (SFGCO) at the forefront of the green transition. Here's a more focused look at the future of these two sectors, particularly from the perspective of investment opportunities in Saudi Arabia and the broader global landscape."
      />
      <Investments sectionDetails={false} />
      <NewsLetter />
    </>
  );
}
